name: "Nixpacks continuous delivery"
description: "Builds a Docker image and push to ghcr"
branding:
  icon: "box"
  color: "blue"
inputs:
  preset:
    description: "Build preset (build-multiarch or build-amd64)"
    required: false
    default: "build-multiarch"
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push Docker images
      uses: iloveitaly/github-action-nixpacks@1015581ad805f3829ad4bdd5deb892e3b5c525b8
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
        platforms: ${{ inputs.preset != 'build-amd64' && 'linux/amd64,linux/arm64' || '' }}
        cache: true
        cache_tag: ${{ env.IMAGE_NAME }}:latest
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository }}
